import Header from "@/components/Header";
import PromptInput from "@/components/PromptInput";
import ClientProvider from "../components/ClientProvider";

import "../styles/globals.css";

export const metadata = {
    title: "Ashraf AI art Gallery",
    description: "Generated by Ashraf Khan",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <ClientProvider>
                    <Header />

                    <PromptInput />
                    {children}
                </ClientProvider>
            </body>
        </html>
    );
}
